apiVersion: v1
kind: Service
metadata:
  name: poisvc
  namespace: default
  labels:
    app: poisvc
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: poi
