apiVersion: v1
kind: Service
metadata:
  name: tripviewersvc
  namespace: default
  labels:
    app: tripviewersvc
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: tripviewer