apiVersion: v1
kind: Service
metadata:
  name: userpjavasvc
  namespace: default
  labels:
    app: userpjavasvc
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: userpjava